debug: true
discord:
  token:
  status: "Kotone-DiVE is running! | .help"
db:
  kind: bbolt
  path: bbolt.db
voices:
  watson:
    enabled: true
    token:
    api:
  gtts:
    enabled: true
  gcp:
    enabled: false
    token: 
  azure:
    enabled: false
    key: 
    region: 
guild:
  prefix: .
  lang: japanese
  maxchar: 100
  voice: # Values under this section are not verified before running! Be careful
    source: watson
    type: ja-JP_EmiVoice
  readbots: false
  policy: allow
  policylist: {}
  replace: {}
